# Spawn/Join

spawn-location:
  world: "Spawn"
  x: 0
  y: 135
  z: 0
  yaw: 90.0
  pitch: 0.0

## Auto Restart

duration: 1 # In Hours, 72000

## GGWave

ggwave-time: 30 # In Seconds
gg-list:
  - "&a&lGG!"
  - "&b&lGG!"
  - "&c&lGG!"
entry-commands:
  - "eco give %player% 100"